# Generated by Django 5.0 on 2024-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
